### ISSUE TITLE
OutOfMemoryError running in Ubuntu VM

### ISSUE THREAD

**Issue by crfloyd** [hyness/spring-cloud-config-server#10]
I have been using this this compose file locally without issue. I have deployed it to an Ubuntu VM in Azure but every time I `docker-compose up`, It throws an error starting up stating:
 `Caused by: java.lang.OutOfMemoryError: Java heap space
        at com.jcraft.jsch.KeyPairRSA.parse(KeyPairRSA.java:223) ~[jsch-0.1.54.jar!/:na]
        at com.jcraft.jsch.KeyPair.load(KeyPair.java:943) ~[jsch-0.1.54.jar!/:na]
        at org.springframework.cloud.config.server.ssh.PrivateKeyValidator.isPrivateKeyFormatCorrect(PrivateKeyValidator.java:82) ~[spring-cloud-config-server-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]`

I have tried setting the JVM_OPTS environment variable in the compse file for Xmx and Xms but this does not seem to help. I have also tried VMs with both 1gb and 2gb of system memory. Nothing but this container runs on the VM.

**Comment by crfloyd** [comment]
This turned out to be an incorrect environment variable format. Closing.
