### ISSUE TITLE
Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin

### ISSUE THREAD

**Issue by vishnudxb** [hyness/spring-cloud-config-server#60]
I am getting this below error when trying to set `SPRING_CLOUD_CONFIG_SERVER_GIT_URI` to `ssh://git@github.com:< my user>/<my repo>repo.git` 
```
Caused by: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:251) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.cloneToBasedir(JGitEnvironmentRepository.java:589) ~[spring-cloud-config-server-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.initClonedRepository(JGitEnvironmentRepository.java:340) ~[spring-cloud-config-server-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.JGitEnvironmentRepository.afterPropertiesSet(JGitEnvironmentRepository.java:256) ~[spring-cloud-config-server-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository.afterPropertiesSet(MultipleJGitEnvironmentRepository.java:66) ~[spring-cloud-config-server-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	... 161 common frames omitted
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://git@github.com:user/repo.git
: not found.
	at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:132) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:107) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.transport.Transport.open(Transport.java:553) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.transport.Transport.open(Transport.java:429) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.transport.Transport.open(Transport.java:308) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.transport.Transport.open(Transport.java:277) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:235) ~[org.eclipse.jgit-5.1.3.201810200350-r.jar!/:5.1.3.201810200350-r]
	... 169 common frames omitted

```

Any idea ?

**Comment by hyness** [comment]
Hello @vishnudxb,

You are using an incorrect URL. You need to remove the `ssh://` prefix. On your repo, there is a code button that shows the URL you should use for ssh and has a copy button

**Comment by vishnudxb** [comment]
@hyness  I tried that as well but getting the same error `git@github.com:user/repo.git`

**Comment by hyness** [comment]
@vishnudxb, if it’s not the URL, then it’s probably an issue with your ssh keys. I did a quick Google, and it’s a fairly common issue. This image does work when configured properly. Check the spring cloud config documentation linked in this repo to see how to configure ssh keys

**Comment by vishnudxb** [comment]
I am running this image in k8s. I have given the ssh key as a k8s secret and I tested if its an issue with the ssh key by manually  pulling the repo inside the container. I can successfully able to clone the repo inside the container manually however when setting the env it throws the above error. So not sure if it's an issue with the sshkey

**Comment by vishnudxb** [comment]
I also tried with https as well but again same error `https://<username>:<password>@github.com/<org>/repo.git`

**Comment by hyness** [comment]
@vishnudxb you should read this section of the documentation. There are separate properties for specifying the username and password. It doesn’t go into the URL. It also mentions where the ssh keys should be stored. The docs also mention that JGit requires RSA keys in PEM format.

https://docs.spring.io/spring-cloud-config/docs/3.0.4/reference/html/#_authentication

**Comment by vishnudxb** [comment]
@hyness  I use the RSA keys in PEM format. When I set env something like this `SPRING_CLOUD_CONFIG_SERVER_GIT_URI=git@github.com:<org>/<repo>.git`  It throws an error like below

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultEnvironmentRepository' defined in class path resource [org/springframework/cloud/config/server/config/DefaultRepositoryConfiguration.class]: Invocation of init method failed; nested exception is org.eclipse.jgit.api.errors.TransportException: git@github.com:<org>/<repo>.git
:
   is not a valid repository name
  Visit https://support.github.com/ for help
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1464) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1428) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1319) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1206) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1168) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:668) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	... 148 common frames omitted
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:<org>/<repo>.git
:
   is not a valid repository name
  Visit https://support.github.com/ for help
```
P.S (In orignal code, I replace the values of org and repo)

**Comment by hyness** [comment]
@vishnudxb , I just tested the image against a private ssh repository hosted at github, and the image works just fine.  I will see about adding a test to the build script, but your issue is with how you are configuring the image.  This is the command I used with the repository url obfuscated

`docker run --rm --name=test -it -p 8888:8888 -v $HOME/.ssh:/root/.ssh hyness/spring-cloud-config-server --spring.cloud.config.server.git.uri=git@github.com:user/private-github-repo.git --spring.cloud.config.server.git.default-label=main`

This also isn't an issue with this image's use in kubernetes.  I have used this image in production with kubernetes extensively.  You need to read the documentation for further assistance, which you have demonstrated you haven't done.  Opening an issue is not an appropriate method for asking for help about configuration issues.  There is a discussions section for asking such questions.  Closing this issue.

**Comment by fennekit** [comment]
> @vishnudxb , I just tested the image against a private ssh repository hosted at github, and the image works just fine. I will see about adding a test to the build script, but your issue is with how you are configuring the image. This is the command I used with the repository url obfuscated
> 
> `docker run --rm --name=test -it -p 8888:8888 -v $HOME/.ssh:/root/.ssh hyness/spring-cloud-config-server --spring.cloud.config.server.git.uri=git@github.com:user/private-github-repo.git --spring.cloud.config.server.git.default-label=main`
> 
> This also isn't an issue with this image's use in kubernetes. I have used this image in production with kubernetes extensively. You need to read the documentation for further assistance, which you have demonstrated you haven't done. Opening an issue is not an appropriate method for asking for help about configuration issues. There is a discussions section for asking such questions. Closing this issue.

**Comment by hyness** [comment]
Hello @fennekit , thank you so much for verifying the image works as expected with SSH keys and the change required with CNB.  I'll get that added to the README
